Repository HandBrake/HandBrake, pull requests merged in 2019-08, with the labels that each got.

#2126 audio_resample: set input and output samplerate
  libhb/audio_resample.c
  libhb/audio_resample.h
  libhb/decavcodec.c
  libhb/declpcm.c
  libhb/encavcodecaudio.c
Labels: Bug

#2234 contrib: Update to FFmpeg 4.2.
  contrib/ffmpeg/A01-avutil-mem-Fix-invalid-use-of-av_alloc_size.patch
  contrib/ffmpeg/A10-mpeg-quarter-sample.patch
  contrib/ffmpeg/module.defs
Labels: Enhancement

#2238 Create A12-videotoolbox-smpte2084-hlg-transfer.patch for FFmpeg
  contrib/ffmpeg/A12-videotoolbox-smpte2084-hlg-transfer.patch
Labels: Enhancement

#2151 Added linux support for amf encoder through vulkan.
  contrib/ffmpeg/A12-FFmpeg-devel-Vulkan-support.patch
  libhb/vce_common.c
  make/configure.py
Labels: Enhancement, Upstream Enhancement
