Repository HandBrake/HandBrake, pull requests merged in 2020-03, with the labels that each got.

#2654 contrib: x265: Don't redundantly set CMAKE_SYSTEM_NAME to the triple when cross compiling for windows
  contrib/x265_10bit/module.defs
  contrib/x265_12bit/module.defs
  contrib/x265_8bit/module.defs
Labels: Enhancement

#2605 gtk: Link to ole32 on mingw
  gtk/configure.ac
Labels: Bug

#2622 ffmpeg: support 'H265' FourCC in AVI.
  contrib/ffmpeg/A01-riff-tag-h265-in-avi.patch
Labels: Upstream Issue

#2720 macosx: Pass compiler optimization level to Xcode.
  macosx/HandBrake.xcodeproj/project.pbxproj
  macosx/module.defs
Labels: Enhancement
