Repository HandBrake/HandBrake, pull requests merged in 2021-07, with the labels that each got.

#3651 Update ko.po
  gtk/po/ko.po
Labels: Awaiting Feedback

#3657 WinGui: Fix several fields from presets not being properly applied
  win/CS/HandBrakeWPF/Services/Encode/Model/EncodeTask.cs
  win/CS/HandBrakeWPF/ViewModels/VideoViewModel.cs
Labels: Bug

#3662 qsv: update mfx_dispatch to API 1.35
  contrib/libmfx/A00-fix-dummy-session.patch
  contrib/libmfx/module.defs
  libhb/qsv_common.c
Labels: Enhancement
