Repository HandBrake/HandBrake, pull requests merged in 2024-04, with the labels that each got.

#5922 LinGui: add a dropdown menu to the "Open Source" button
  gtk/src/callbacks.c
  gtk/src/ui/ghb.ui
  gtk/src/ui/menu.ui
Labels: Enhancement, LinuxUI

#5923 Use a libdovi tar package that includes the 3rd party dependencies.
  contrib/libdovi/module.defs
Labels: Enhancement

#5993 libhb: limit the possible frame rates to avoid overflows.
  libhb/decavcodec.c
Labels: Bug

#5998 [LinuxGUI] Update existing translations
  NEWS.markdown
  gtk/po/af.po
  gtk/po/bg.po
  gtk/po/ca.po
  gtk/po/co.po
  gtk/po/cs.po
  gtk/po/de.po
  gtk/po/es.po
  gtk/po/eu.po
  gtk/po/fi.po
  gtk/po/fr.po
  gtk/po/he.po
  gtk/po/hr.po
  gtk/po/it.po
  gtk/po/ja.po
  gtk/po/ka.po
  gtk/po/ko.po
  gtk/po/nl.po
  gtk/po/no.po
  gtk/po/pl.po
  gtk/po/pt.po
  gtk/po/pt_BR.po
  gtk/po/ro.po
  gtk/po/ru.po
  gtk/po/si.po
  gtk/po/sk.po
  gtk/po/sl_SI.po
  gtk/po/sv.po
  gtk/po/th.po
  gtk/po/tr.po
  gtk/po/uk_UA.po
  gtk/po/zh_TW.po
Labels: Enhancement

#5997 [winGUI] Update existing translations
  NEWS.markdown
  win/CS/HandBrakeWPF/Properties/Resources.bg.resx
  win/CS/HandBrakeWPF/Properties/Resources.ca.resx
  win/CS/HandBrakeWPF/Properties/Resources.co.resx
  win/CS/HandBrakeWPF/Properties/Resources.cs-CZ.resx
  win/CS/HandBrakeWPF/Properties/Resources.de.resx
  win/CS/HandBrakeWPF/Properties/Resources.el.resx
  win/CS/HandBrakeWPF/Properties/Resources.es.resx
  win/CS/HandBrakeWPF/Properties/Resources.et.resx
  win/CS/HandBrakeWPF/Properties/Resources.eu.resx
  win/CS/HandBrakeWPF/Properties/Resources.fa-IR.resx
  win/CS/HandBrakeWPF/Properties/Resources.fi.resx
  win/CS/HandBrakeWPF/Properties/Resources.fr.resx
  win/CS/HandBrakeWPF/Properties/Resources.it.resx
  win/CS/HandBrakeWPF/Properties/Resources.ja.resx
  win/CS/HandBrakeWPF/Properties/Resources.ko.resx
  win/CS/HandBrakeWPF/Properties/Resources.nl.resx
  win/CS/HandBrakeWPF/Properties/Resources.pl.resx
  win/CS/HandBrakeWPF/Properties/Resources.pt-BR.resx
  win/CS/HandBrakeWPF/Properties/Resources.ru.resx
  win/CS/HandBrakeWPF/Properties/Resources.th.resx
  win/CS/HandBrakeWPF/Properties/Resources.tr.resx
  win/CS/HandBrakeWPF/Properties/Resources.uk.resx
  win/CS/HandBrakeWPF/Properties/Resources.zh-Hans.resx
  win/CS/HandBrakeWPF/Properties/Resources.zh-Hant.resx
  win/CS/HandBrakeWPF/Properties/ResourcesTooltips.pt-BR.resx
  win/CS/HandBrakeWPF/Properties/ResourcesTooltips.tr.resx
Labels: Enhancement

#6003 scan: limit errors during audio scan
  libhb/decavcodec.c
  libhb/handbrake/common.h
  libhb/scan.c
Labels: Bug
